name: Cypress Tests

on:
  push:
    branches: [ "develop" ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Rodar json-server
        run: npx json-server --watch backend/db.json &

      - name: Rodar Cypress
        run: npx cypress run